### ISSUE TITLE
c++ bug

### ISSUE THREAD

**Issue by pbecchi** [tcsaba101/SG21#3] opened 2017-09-25 07:59 UTC
I cannot compile myself the branch ...... can you give me the compilation error messages?

**Comment by pbecchi** [comment] 2017-09-25 08:13
i was trying to find the code you have posted in the github but you have not uploaded that code ...
It is impossible to help if I don't see the code...........
send a message when you upload!

**Comment by tcsaba101** [comment] 2017-09-25 11:43
The branch: SG21/Cloud_testing

**Comment by tcsaba101** [comment] 2017-09-25 11:46
I have compiled, debugged the latest code in Atmel Studio, then Committed and Pushed to "Cloud_testing" branch.  
Should I do something else?
If I am understanding merging is needed only if there are two or more developers in different branches.

**Comment by pbecchi** [comment] 2017-09-25 12:31
If I understand the code you have uploaded is not the one with the bug.
You have uploaded in the branch cloud_testing all the modification that you have done, compiled and tested up to now, what's about the other branches?
If it is ok for you I suggest you upload the code with the bug in a new branch, so that you keep the above work separate!

**Comment by tcsaba101** [comment] 2017-09-25 12:49
This is function:
https://github.com/tcsaba101/SG21/blob/394668d810bf12b83af919b33e414d1c7f90065f/main.cpp#L1389
This is calling:
https://github.com/tcsaba101/SG21/blob/394668d810bf12b83af919b33e414d1c7f90065f/main.cpp#L1749
This is from I imported the coding:
https://github.com/tcsaba101/SG21/blob/48d0b44f2c56005d0ab87575c02a088035df73e8/server.cpp#L350

**Comment by tcsaba101** [comment] 2017-09-25 12:54
The branches are:
master: orig 217 code  
Options&Network: All new codes, including Sensors, not Cloud related code
Cloud_testing pulled from Options&......: all the code I have written

**Comment by tcsaba101** [comment] 2017-09-25 13:02
I made several commits in the Options&... branch.
Unfortunately I couldn't compile it error free before Sensors integration, because of a lot of undefined objects. So I decided to put all those code parts that branch.
That compiled error free.

Then I opened the Cloud... branch and I put all additional cloud related code to this branch.

Please suggest the working strategy for the future if this is not a good practice.

**Comment by pbecchi** [comment] 2017-09-25 13:25
Now it is clear ...I was looking to the wrong place...it is in Main.cpp not in server.cpp!
I will have a look ...it is looping during execution?
Options&Network has be compiled and it tested OK?
Can I working on it? I will extract parts of that i will merge it to my code, if I don't understand , I will post questions as separate issues....please give me your comments there.
Thanks

**Comment by tcsaba101** [comment] 2017-09-25 15:06
It is not looping itself, but it is in a "loose" loop when calling from the main loop.

I have compiled ok, the  Options branch, but I haven't tested on hw.
Now I have created Sensors branch pruning Cloud related things out. 
I don't know whether it is useful or not for you.

**Comment by pbecchi** [comment] 2017-09-26 09:37
I will clone your repo now and work on it!
Please avoid to make modification to options&network branch while I am doing integration to Esp32 code.
I will extract all your branch differences and Port it to my code under #ifdef SG21 #endif statements.
For questions and clarifications I will open issues here!

**Comment by tcsaba101** [comment] 2017-09-26 10:03
I still have to debug some part of sensors and I have plans about minor improvements. 
I will open a new branch from Options branch and put my developments there.
Can I delete the Sensors branch based on your comment?

**Comment by pbecchi** [comment] 2017-09-26 10:24
I dont know what it is better....... if you do your modifications now......I better wait
If you do it when you come back from Elba.... I can try to integrate before and you can than make pull request to my code.
I have already some questions ....look to new issues!

**Comment by tcstmarkt** [comment] 2017-10-12 07:34
Did you have a chance to analyze this problem?
Or any answer arrived to your forum question?

**Comment by pbecchi** [comment] 2017-10-12 12:25
I am progressing with the integration ,but I am not ready yet with compilation.
What I suggest is to take all cloud related code and to put it in cloud.cpp (see pull request) and to conditional compile (or leave out the Debug code). You may help me on extracting the Debug code from SG21 and put it in #ifdef SG21DEBUG ....#endif loops!

**Comment by tcstmarkt** [comment] 2017-10-12 13:37
T think I did put all the debug code to #ifdef ... #endif packages. Altough no difference between the OS217, and SG21 packages.
I need it for development, but I can separete from the original if you need.
The DEBUG_PRINT macros should stay as it is.
All the debug related codes are compiling depending on SERIAL_DEBUG value.
If it is 0 no debug related code will be compiled no printing to Serial Monitor.

The pull request list is still empty, what was your intention?

**Comment by pbecchi** [comment] 2017-10-12 14:38
Today I am out,  I maydo pull request tonight or tomorrow morning!
Regarding debug...  I also use DEBUG_PRINT  and we can leave all those,  just use #ifdef for other debug lines like print_today_log jtag and other similar stuff.

**Comment by pbecchi** [comment] 2017-10-13 08:06
I have created a fork in GitHub.com/pbecchi/SG21 in the branch Cloud testing new you can find main.cpp cloud.cpp and cloud.h !
If I try to pull-request it bring a lot of other files... It is better if you take those files yourself!
Paolo
PS. I have not compiled yet so please check cloud.cpp from errors !



---- On gio, 12 ott 2017 15:37:41 +0200 notifications@github.com wrote ----

T think I did put all the debug code to #ifdef ... #endif packages. Altough no difference between the OS217, and SG21 packages.
I need it for development, but I can separete from the original if you need.
The DEBUG_PRINT macros should stay as it is.
All the debug related codes are compiling depending on SERIAL_DEBUG value.
If it is 0 no debug related code will be compiled no printing to Serial Monitor.

The pull request list is still empty, what was your intention?

**Comment by tcsaba101** [comment] 2017-10-13 08:56
I would  make a new branch in my repository with latest commits and separate main and cloud as you introduced.

**Comment by pbecchi** [comment] 2017-10-17 08:43
Hi

I have created a new domain smartgarden.cloud where I will put all my projects including SmartSolenoid , I will create a new WordPress website  that will be as corporate as possible. I may also add a forum to the site!

@Csaba : have you seen my message on SG21 transcoding? I am almost ready with Esp32 version but I have a problem with SPIFFS library!

As soon as I am ready shall I upload to gitlab?

You wantto test the code on Esp8266 ?.......you could start now!

@Mike : for UI how we proceed?

Paolo

---- On ven, 13 ott 2017 10:56:55 +0200 notifications@github.com wrote ----

I would make a new branch in my repository with latest commits and separate main and cloud as you introduced.

**Comment by tcsaba101** [comment] 2017-10-25 06:29
Finally I have solved this c++ bug.
The problem is handling strings stored on program space (or flash space).

This function calling:
SG21/main.cpp Line 1749 in 394668d
cloud_json_stations_attrib(PSTR("masop"), ADDR_NVM_MAS_OP, postval); 
put the "masop" string in flash.

In the function: 
SG21/main.cpp Line 1389 in 394668d
 void cloud_json_stations_attrib(const char* name, int addr, char* postval_pt) 
the 'name' pointer is pointing to a flash area not to SRAM, as the c++ default is SRAM pointer in the case of all string operations.
There are string operators what works with flash pointers with _P suffix:
strcpy_P(tmp_buffer, (PGM_P)name); will copy the right string from flash

Serial.print does not have a _P variant, there is a nice discussion about:
https://forum.arduino.cc/index.php?topic=50197.0

The source of my code is works:
SG21/server.cpp Line 350 in 48d0b44
 void server_json_stations_attrib(const char* name, int addr) 
this works, because in Ethercard function:
bfill.emit_p(PSTR("\"$F\":["), name);
the $F means the "name" is a flash pointer.

:-))

I close this issue now.

**Closed as completed by tcsaba101** 2017-10-25 06:29 UTC

**Comment by pbecchi** [comment] 2017-10-25 07:38
You should consider that Esp family do not use progmem type flashh storage all storage is in Ram!

**Comment by tcsaba101** [comment] 2017-10-25 10:49
Ray using this kind of storage & functions often in OS.
In ESP you have to load to RAM all the strings from the flash area?

**Comment by pbecchi** [comment] 2017-10-25 17:08
PROGMEM is used to save RAM in all AVR MCU. It is absolutely necessary to use it 9f you want to compile OS in Arduino UNo or similar 2k RAM boards
ESP8266 and ESP32 have a lot of RAM (80k and 256k) so PROGMEM is useless! Most (but not all ) PROGMEM call have been left for compatibility but RAM is used not FLASH!
